 # Week 2:
 File: DSC550_Paulovici_Exercise_2_2.py (.ipynb)<br>
 Name: Kevin Paulovici<br>
 Date: 3/22/2020<br>
 Course: DSC 550 Data Mining (2205-1)<br>
 Assignment: 2.2 Exercise: Build your Text Classifiers

 ## Part 1
 You can find the data for this exercise in the Weekly Resources: Week 2 Data Files.Preparing Text: For this part, you will start by reading the Income.json (controversial-comments.json) file into a DataFrame.

In [1]:
import json
import pandas as pd
from pandas.io.json import json_normalize

# with open("controversial-comments_subset.json") as fileIn:
# with open("controversial-comments.json") as fileIn:
#     count = 0

#     # read each line as a json obj
#     for line in fileIn:
#         line = line.strip()
#         data = json.loads(line)

#         # create the dataframe for the first obj else append data
#         if count == 0:
#             df = json_normalize(data)            
#         else:
#             df2 = json_normalize(data)
#             df = df.append(df2, ignore_index=True)
        
#         count += 1

with open("controversial-comments.json") as f:
    df = pd.DataFrame(json.loads(line) for line in f)  

df.head(10)        


con                                                txt
0    0  Well it's great that he did something about th...
1    0                       You are right Mr. President.
2    0  You have given no input apart from saying I am...
3    0  I get the frustration but the reason they want...
4    0  I am far from an expert on TPP and I would ten...
5    0  Thanks for playing. [I feel like her now](http...
6    0                                          [deleted]
7    0  i cant be racist, i have a black friend  \n\nl...
8    0  Nope. You're right that they are both smoke an...
9    0  &lt;That's exactly what it means. especially w...

 ### Part A
 Convert all text to lowercase letters.

In [2]:
df["txt"] = df["txt"].str.lower()
df.head(5)



con                                                txt
0    0  well it's great that he did something about th...
1    0                       you are right mr. president.
2    0  you have given no input apart from saying i am...
3    0  i get the frustration but the reason they want...
4    0  i am far from an expert on tpp and i would ten...

 ### Part B
 Remove all punctuation from the text.

In [3]:
import unicodedata
import sys

punctuation = dict.fromkeys(i for i in range(sys.maxunicode) if unicodedata.category(chr(i)).startswith('P'))

df.txt = df.txt.apply(lambda x: x.translate(punctuation))
df.head(5)


con                                                txt
0    0  well its great that he did something about tho...
1    0                         you are right mr president
2    0  you have given no input apart from saying i am...
3    0  i get the frustration but the reason they want...
4    0  i am far from an expert on tpp and i would ten...

 ### Part C
 Remove stop words.

In [4]:
from nltk.corpus import stopwords
# import nltk
# nltk.download('stopwords')

# load stop words
stop_words = stopwords.words('english')

# TODO: get lambda function working
# remove stop_words
# df.txt.apply(lambda x: [item for item in x if item not in stop_words])

# remove stop words
def stopWords(sentence):
    tokens = sentence.split()
    w = [item for item in tokens if item not in stop_words]
    return ' '.join(w)

df.txt = df.txt.apply(stopWords)
df.head(5)


con                                                txt
0    0  well great something beliefs office doubt trum...
1    0                                 right mr president
2    0    given input apart saying wrong argument clearly
3    0  get frustration reason want way foundation com...
4    0  far expert tpp would tend agree lot problems u...

 ### Part D
 Apply NLTK’s PorterStemmer.

In [5]:
from nltk.stem.porter import PorterStemmer

# creater stemmer
porter = PorterStemmer()

# TODO: get lambda function working
# df.txt.apply(lambda x: [porter.stem(word) for word in x])

def stem_sentences(sentence):
    tokens = sentence.split()
    stemmed_tokens = [porter.stem(token) for token in tokens]
    return ' '.join(stemmed_tokens)

df.txt = df.txt.apply(stem_sentences)
df.head(5)


con                                                txt
0    0  well great someth belief offic doubt trump wou...
1    0                                    right mr presid
2    0       given input apart say wrong argument clearli
3    0  get frustrat reason want way foundat complex p...
4    0  far expert tpp would tend agre lot problem und...

 ### Part E
 Use a Tf-idf vector instead of the word frequency vector.

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

text_data = df.txt
tfidf = TfidfVectorizer()
feature_matrix = tfidf.fit_transform(text_data)

print(feature_matrix)
print(feature_matrix.toarray())
print(tfidf.vocabulary_)


  (0, 221985)	0.1537481966521577
  (0, 75288)	0.19246237681546385
  (0, 183220)	0.33755498473950624
  (0, 28984)	0.2440606522216381
  (0, 147089)	0.2002750411567945
  (0, 56530)	0.2242722976593182
  (0, 206476)	0.10681416871771479
  (0, 225787)	0.12609962495896018
  (0, 67000)	0.2162181524366245
  (0, 212329)	0.3009578712227802
  (0, 113895)	0.1369226316954281
  (0, 166176)	0.30525177773409623
  (0, 82957)	0.23786352811964573
  (0, 146186)	0.1706949295738838
  (0, 46817)	0.5204901080720826
  (0, 220153)	0.2054606142867531
  (1, 170560)	0.43148287653570905
  (1, 138609)	0.7725190345000794
  (1, 159442)	0.4658721590646248
  (2, 73269)	0.35162873105037284
  (2, 116053)	0.5500675150855808
  (2, 22812)	0.44372126622443014
  (2, 175157)	0.21906058490251382
  (2, 226078)	0.30011522433412624
  (2, 23684)	0.3322871207911399
  :	:
  (949996, 62386)	0.0895205319894615
  (949996, 56772)	0.09351674720406025
  (949996, 43376)	0.25302983815811486
  (949996, 54252)	0.09007314503803204
  (949996, 22394

MemoryError: 

 ## Part 2
 Complete the 5.3 Encoding Dictionaries of Features examples. Be sure to read the Discussion concerning keeping track of how many times a word is used in a document. Also be sure to run the example and read the Discussion from 6.9 Weighting Word Importance. Finally, consider tokenizing words or sentences (see 6.4) and tagging parts of speech (see 6.7) Be sure to review how to encode days of the week (see 7.6). <br><br>
 You can start with the #1 program and add to it or you can start a new program.

 ### 5.3 Encoding Dictionaries of Features - book examples

In [7]:
from sklearn.feature_extraction import DictVectorizer

# create dict
data_dict = [{"Red": 2, "Blue": 4},
             {"Red": 4, "Blue": 3},
             {"Red": 1, "Yellow": 2},
             {"Red": 2, "Yellow": 2}]

# create dict vectorizer
dictvectorizer = DictVectorizer(sparse=False)

# convert dict to feature matrix
features = dictvectorizer.fit_transform(data_dict)

# view feature matrix
features


array([[4., 2., 0.],
       [3., 4., 0.],
       [0., 1., 2.],
       [0., 2., 2.]])

In [8]:
# get feature names
feature_names = dictvectorizer.get_feature_names()

# view feature names
feature_names


['Blue', 'Red', 'Yellow']

In [9]:
# create dataframe to output data better
import pandas as pd

# create df from features
pd.DataFrame(features, columns=feature_names)


Blue  Red  Yellow
0   4.0  2.0     0.0
1   3.0  4.0     0.0
2   0.0  1.0     2.0
3   0.0  2.0     2.0

In [10]:
# create word counts dictionaries for four documents
doc_1_word_count = {"Red": 2, "Blue": 4}
doc_2_word_count = {"Red": 4, "Blue": 3}
doc_3_word_count = {"Red": 1, "Yellow": 2}
doc_4_word_count = {"Red": 2, "Yellow": 2}

# create list 
doc_word_counts = [doc_1_word_count, doc_2_word_count, doc_3_word_count, doc_4_word_count]

# convert list of word count dicts into feature matrix
dictvectorizer.fit_transform(doc_word_counts)



array([[4., 2., 0.],
       [3., 4., 0.],
       [0., 1., 2.],
       [0., 2., 2.]])

 ### 6.4 Tokenizing Text - book examples

In [11]:
from nltk.tokenize import word_tokenize

# create text
string = "The science of today is the technology of tomorrow"

# tokenize words
word_tokenize(string) # error

# work around for viewing only
# string.split()


['The', 'science', 'of', 'today', 'is', 'the', 'technology', 'of', 'tomorrow']

In [12]:
# Tokenize sentences
from nltk.tokenize import sent_tokenize

# create text
string = "The science of today is the technology of tomorrow. Tomrow is today."

# tokenize sentences
sent_tokenize(string) # error

# work around for viewing only
# string.split(".")


['The science of today is the technology of tomorrow.', 'Tomrow is today.']

 ### 6.7 Tagging Parts of Speech - book examples

In [13]:
from nltk import pos_tag
from nltk import word_tokenize

# create text
text_data = "Chris loved outdoor running"

# use pre-trained part of speech tagger
text_tagged = pos_tag(word_tokenize(text_data))

# show parts of speech
text_tagged

[word for word, tag in text_tagged if tag in ['NN', 'NNS', 'NNP', 'NNPS']]


['Chris']

In [14]:
import nltk
import sklearn
from sklearn.preprocessing import MultiLabelBinarizer

# create text
tweets = ["I am eating a burrito for breakfast", 
"Political science is an amazing field", 
"San Francisco is an awesome city"]

# Create list
tagged_tweets = []

# tag each word and each tweet
for tweet in tweets:
    tweet_tag = nltk.pos_tag(nltk.word_tokenize(tweet))
    tagged_tweets.append([tag for word, tag in tweet_tag])

# use one-hot encoding to conver the tags into features
one_hot_multi = MultiLabelBinarizer()
one_hot_multi.fit_transform(tagged_tweets)


array([[1, 1, 0, 1, 0, 1, 1, 1, 0],
       [1, 0, 1, 1, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 0, 0, 0, 1]])

In [15]:
one_hot_multi.classes_


array(['DT', 'IN', 'JJ', 'NN', 'NNP', 'PRP', 'VBG', 'VBP', 'VBZ'],
      dtype=object)

 ### 6.9  - Weighting Word Importance book examples

In [16]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

# create_text 
text_data = np.array(["I love Brazil. Brazil!", 
"Sweden is best", "Germany beats both"])

# create the tf-idf feature matrix
tfidf = TfidfVectorizer()
feature_matrix = tfidf.fit_transform(text_data)

# show tf-idf feature matrix
feature_matrix


<3x8 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [17]:
# show tf-idf featyre matrix as dense matrix
feature_matrix.toarray()


array([[0.        , 0.        , 0.        , 0.89442719, 0.        ,
        0.        , 0.4472136 , 0.        ],
       [0.        , 0.57735027, 0.        , 0.        , 0.        ,
        0.57735027, 0.        , 0.57735027],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027,
        0.        , 0.        , 0.        ]])

In [18]:
# show feature names
tfidf.vocabulary_



{'love': 6,
 'brazil': 3,
 'sweden': 7,
 'is': 5,
 'best': 1,
 'germany': 4,
 'beats': 0,
 'both': 2}

 ### 7.6  Encoding Days of the week - book examples

In [19]:
import pandas as pd

# create dates
dates = pd.Series(pd.date_range("2/2/2002", periods=3, freq="M"))

# show days of the week
dates.dt.weekday_name


0    Thursday
1      Sunday
2     Tuesday
dtype: object

In [20]:
# show days of the week
dates.dt.weekday


0    3
1    6
2    1
dtype: int64

 ### Part A
 Provide me with an example (besides counting words in a document) of how these techniques could be used. (Just a couple sentences.)
 We can use the words from some source to help determine a few things besides just word count. For example, if we consider an article, we can determine the subject of the article by how often a word appears. If economy or economics appears often we can say the subject or point or the article is about economics. Similiarlly, we can determine the mood or gender by looking for key words (e.g., good, great, she, him, etc).

 ### Part C
 You can create a datafile file or use one from the course resources. You must use DataFrames!

In [21]:
# create a dataframe for Part B.
import pandas as pd

data = [["Person_1", "I hate the outdoors!"],
        ["Person_2", "The outdoors is okay."],
        ["Person_3", "I can't stand to be inside! Outside is my home."]]

df = pd.DataFrame(data, columns = ['Name', "Statement"])

df


Name                                        Statement
0  Person_1                             I hate the outdoors!
1  Person_2                            The outdoors is okay.
2  Person_3  I can't stand to be inside! Outside is my home.

 ### Part B
 Then implement at least 3 of these Text techniques in a program demonstrating how your example could be accomplished. Be sure to include lots of comments.

In [22]:
from nltk.tokenize import word_tokenize

# mood and subject are what we are looking to determine from the df

# create list of words for mood
good = ["good", "happy", "love"]
bad = ["bad", "hate", "sad"]

# tokenize statements of each row to compare to list for mood (example 6.4)
statements = df.Statement

# if the tokenized word matches our mood list they get a point
# the higher points determins the mood of the statement
for s in statements:
    good_mood = 0
    bad_mood = 0

    wt = word_tokenize(s)

    for word in wt:
        if word in good:
            good_mood +=1
        
        elif word in bad:
            bad_mood +=1
    
    if good_mood > bad_mood:
        print(s, "This persons statement indicates a good mood about the subject.\n")
    elif bad_mood > good_mood:
        print(s, "This persons statement indicates a bad mood about the subject.\n")
    else:
        print(s, "This persons statement didn't indicate a good or bad mood about the subject.\n")


I hate the outdoors! This persons statement indicates a bad mood about the subject.

The outdoors is okay. This persons statement didn't indicate a good or bad mood about the subject.

I can't stand to be inside! Outside is my home. This persons statement didn't indicate a good or bad mood about the subject.



In [23]:
# since we also want to try to predict the subject, lets wigh the words of the statements. (example 6.9)
from sklearn.feature_extraction.text import TfidfVectorizer
from pprint import pprint

tfidf = TfidfVectorizer()
feature_matrix = tfidf.fit_transform(statements)
print(feature_matrix, "\n")
print(feature_matrix.toarray(),"\n")
pprint(tfidf.vocabulary_)

# I initially thought that the subject, outdoors, would be the most important. However, since it is frequent within the document it becomes less important. On the otherhand, the mood (e.g., hate, okay) become the most important word of each persons statement.


  (0, 2)	0.680918560398684
  (0, 11)	0.5178561161676974
  (0, 8)	0.5178561161676974
  (1, 11)	0.45985352875883484
  (1, 8)	0.45985352875883484
  (1, 5)	0.45985352875883484
  (1, 7)	0.604652128305311
  (2, 5)	0.2596634391575384
  (2, 1)	0.3414262179382391
  (2, 10)	0.3414262179382391
  (2, 12)	0.3414262179382391
  (2, 0)	0.3414262179382391
  (2, 4)	0.3414262179382391
  (2, 9)	0.3414262179382391
  (2, 6)	0.3414262179382391
  (2, 3)	0.3414262179382391 

[[0.         0.         0.68091856 0.         0.         0.
  0.         0.         0.51785612 0.         0.         0.51785612
  0.        ]
 [0.         0.         0.         0.         0.         0.45985353
  0.         0.60465213 0.45985353 0.         0.         0.45985353
  0.        ]
 [0.34142622 0.34142622 0.         0.34142622 0.34142622 0.25966344
  0.34142622 0.         0.         0.34142622 0.34142622 0.
  0.34142622]] 

{'be': 0,
 'can': 1,
 'hate': 2,
 'home': 3,
 'inside': 4,
 'is': 5,
 'my': 6,
 'okay': 7,
 'outdoors': 8,
 

In [24]:
# determining parts of speach to see if the statement is about the person (example 6.7)
from nltk import pos_tag
from nltk import word_tokenize

for s in statements:
    text_tagged = pos_tag(word_tokenize(s))

    # print personal pronouns
    personal = [word for word, tag in text_tagged if tag in ["PRP", "PRP$"]]
    print(personal, "\n")


['I'] 

[] 

['I', 'my'] 

